version: "3.3"

services:
  postgresdb:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=jorge
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadminstore:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5051:80
